#!/usr/bin/python3
import math
import sys

def factorize(n):
    factors = []
    for i in range(2, int(math.sqrt(n)) + 1):
        while n % i == 0:
            factors.append(i)
            n //= i
    if n > 1:
        factors.append(n)
    return factors

def factors(filename):
    with open(filename, 'r') as f:
        lines = f.readlines()
    
    for line in lines:
        num = int(line.strip())
        for factor in factorize(num):
            print(f"{num}={factor}*{num//factor}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    
    filename = sys.argv[1]
    factors(filename)
