#!/usr/bin/python3

# Import necessary modules
import sys
from math import sqrt, floor

# Function to find the factorization of a number
def factor(n):
    # Iterate from 2 to the square root of n
    for i in range(2, int(sqrt(n)) + 1):
        # If n is divisible by i, return i and n/i as the factors
        if n % i == 0:
            return i, n // i
    # If no factor is found, return n and 1 (n is prime)
    return n, 1
