#!/usr/bin/python3
import math
import sys

def factorize(n):
    factors = []
    for i in range(2, int(math.sqrt(n)) + 1):
        while n % i == 0:
            factors.append(i)
            n //= i
    if n > 1:
        factors.append(n)
    return factors

def factors_rsa(filename):
    with open(filename, 'r') as f:
        num = int(f.readline().strip())
    primes = factorize(num)
    print(f"{num}={'*'.join(map(str, primes))}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename = sys.argv[1]
    factors_rsa(filename)
