#!/usr/bin/python3

import sys
from math import sqrt, floor

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

def factor(n):
    for i in range(2, int(sqrt(n)) + 1):
        if n % i == 0 and is_prime(i) and is_prime(n // i):
            return i, n // i
    return n, 1
